### ISSUE TITLE
copy_dir dependency is unmaintained?

### ISSUE THREAD

**Issue by michel-slm** [jmgao/pore#96]
`copy_dir` is last released 6 years ago, and depends on an ancient version of walkin (0.1; the latest is 2.x)

This makes packaging `pore` in Linux distributions harder - maybe the first step will be making `copy_dir` a Windows only dependency? On Unix-y systems shelling out to `cp -pr` might be an option

**Comment by jmgao** [comment]
It looks like [fs_extra](https://docs.rs/crate/fs_extra/1.2.0) has an equivalent implementation and is entirely standalone, I'll move over to that.
